// Generated by CoffeeScript 1.12.7

/*
 * CREADOR POR: POL ALCOVERRO
 * Descripción: Directivas de métricas compiladas a JS para gráficos Chart.js en la integración con Learning Dashboard.
 */

(function() {
  var BarChartDirective, LineChartDirective, PieChartDirective, RadarChartDirective, SpeedometerChartDirective, chartReadyPromise, ensureChartReady, getChartMajorVersion, module, taiga;

  taiga = this.taiga;

  module = angular.module("taigaMetrics");

  chartReadyPromise = null;

  ensureChartReady = function() {
    if (chartReadyPromise != null) {
      return chartReadyPromise;
    }
    chartReadyPromise = new Promise(function(resolve, reject) {
      var attempts, checkChart, maxAttempts, registerIfNeeded;
      maxAttempts = 100;
      attempts = 0;
      registerIfNeeded = function() {
        var error;
        if ((window.Chart != null) && (window.Chart.register != null) && (window.Chart.registerables != null) && !window.Chart._taigaMetricsRegistered) {
          try {
            window.Chart.register.apply(window.Chart, window.Chart.registerables);
            window.Chart._taigaMetricsRegistered = true;
            return console.log("✓ Chart.js registered successfully");
          } catch (error1) {
            error = error1;
            return console.error("Error registering Chart.js:", error);
          }
        }
      };
      checkChart = function() {
        attempts++;
        if (window.Chart != null) {
          console.log("✓ Chart.js found, version:", window.Chart.version);
          registerIfNeeded();
          return resolve(window.Chart);
        } else if (attempts < maxAttempts) {
          console.log("Waiting for Chart.js... attempt " + attempts);
          return setTimeout(checkChart, 100);
        } else {
          console.error("Chart.js not loaded after " + maxAttempts + " attempts");
          return reject(new Error("Chart.js not available"));
        }
      };
      return checkChart();
    });
    return chartReadyPromise;
  };

  getChartMajorVersion = function(ChartLib) {
    var major, version;
    version = ChartLib != null ? ChartLib.version : void 0;
    if (version == null) {
      return 0;
    }
    major = parseInt(version.toString().split(".")[0], 10);
    if (isNaN(major)) {
      return 0;
    } else {
      return major;
    }
  };

  RadarChartDirective = function($parse, $timeout) {
    var link;
    link = function(scope, element, attrs) {
      var canvas, canvasId, chart, destroyChart, isRendering, renderChart;
      console.log("RadarChart directive linking, initial data:", scope.data);
      canvasId = "radar-chart-" + (Date.now()) + "-" + (Math.random().toString(36).substr(2, 9));
      canvas = document.createElement('canvas');
      canvas.id = canvasId;
      canvas.width = 400;
      canvas.height = 400;
      element.append(canvas);
      chart = null;
      isRendering = false;
      destroyChart = function() {
        var e;
        if (chart != null) {
          try {
            chart.destroy();
            console.log("Chart destroyed for:", canvasId);
          } catch (error1) {
            e = error1;
            console.error("Error destroying chart:", e);
          }
          return chart = null;
        }
      };
      renderChart = function(data) {
        console.log("RadarChart renderChart called with data:", data);
        if (!data || !data.datasets || data.datasets.length === 0) {
          console.warn("No valid data for radar chart");
          destroyChart();
          return;
        }
        if (isRendering) {
          return;
        }
        isRendering = true;
        return ensureChartReady().then(function(ChartLib) {
          console.log("Chart.js ready, rendering radar chart for:", canvasId);
          return $timeout(function() {
            var baseConfig, ctx, error, majorVersion, ref, ref1;
            try {
              ctx = canvas.getContext('2d');
              if (!ctx) {
                console.error("Could not get canvas context for:", canvasId);
                isRendering = false;
                return;
              }
              destroyChart();
              majorVersion = getChartMajorVersion(ChartLib);
              console.log("Creating radar chart, Chart.js version:", majorVersion);
              baseConfig = {
                type: 'radar',
                data: {
                  labels: data.labels || ['Assigned Tasks', 'Commits', 'Modified Lines'],
                  datasets: data.datasets || []
                },
                options: {
                  responsive: true,
                  maintainAspectRatio: true
                }
              };
              if (majorVersion >= 3) {
                baseConfig.options.scales = {
                  r: {
                    beginAtZero: true,
                    min: 0,
                    max: 100,
                    ticks: {
                      stepSize: 20,
                      callback: function(value) {
                        return value + "%";
                      }
                    }
                  }
                };
                baseConfig.options.plugins = {
                  legend: {
                    display: ((ref = data.datasets) != null ? ref : []).length > 1,
                    position: 'bottom'
                  },
                  tooltip: {
                    callbacks: {
                      label: function(context) {
                        var label, parts, ref1, ref2, value;
                        label = ((ref1 = context.dataset) != null ? ref1.label : void 0) || '';
                        parts = [];
                        if (label) {
                          parts.push(label + ":");
                        }
                        value = (ref2 = context.parsed) != null ? ref2.r : void 0;
                        parts.push((Number(value || 0).toFixed(2)) + "%");
                        return parts.join(' ');
                      }
                    }
                  }
                };
              } else {
                baseConfig.options.scale = {
                  ticks: {
                    beginAtZero: true,
                    max: 100,
                    stepSize: 20,
                    callback: function(value) {
                      return value + "%";
                    }
                  }
                };
                baseConfig.options.legend = {
                  display: ((ref1 = data.datasets) != null ? ref1 : []).length > 1,
                  position: 'bottom'
                };
                baseConfig.options.tooltips = {
                  callbacks: {
                    label: function(tooltipItem, chartData) {
                      var dataset, label, ref2, ref3, ref4, value, valueNumber;
                      dataset = chartData != null ? (ref2 = chartData.datasets) != null ? ref2[tooltipItem.datasetIndex] : void 0 : void 0;
                      label = (dataset != null ? dataset.label : void 0) || '';
                      value = (ref3 = (ref4 = tooltipItem != null ? tooltipItem.yLabel : void 0) != null ? ref4 : tooltipItem != null ? tooltipItem.value : void 0) != null ? ref3 : tooltipItem != null ? tooltipItem.parsed : void 0;
                      valueNumber = Number(value || 0);
                      return label + ": " + (valueNumber.toFixed(2)) + "%";
                    }
                  }
                };
              }
              console.log("Creating chart with config:", baseConfig);
              chart = new ChartLib(ctx, baseConfig);
              return console.log("✓ Radar chart created successfully:", canvasId);
            } catch (error1) {
              error = error1;
              return console.error("Error creating radar chart:", error);
            } finally {
              isRendering = false;
            }
          }, 100);
        })["catch"](function(error) {
          console.error("Chart.js not available:", error);
          return isRendering = false;
        });
      };
      scope.$watch('data', function(newVal, oldVal) {
        console.log("RadarChart data changed:", newVal);
        if (newVal) {
          return renderChart(newVal);
        } else {
          return destroyChart();
        }
      }, true);
      return scope.$on('$destroy', function() {
        console.log("RadarChart directive destroyed:", canvasId);
        return destroyChart();
      });
    };
    return {
      restrict: 'E',
      link: link,
      scope: {
        data: '='
      }
    };
  };

  module.directive("tgRadarChart", ["$parse", "$timeout", RadarChartDirective]);

  SpeedometerChartDirective = function($parse, $timeout) {
    var link;
    link = function(scope, element, attrs) {
      var canvas, canvasId, chart, destroyChart, getColorForValue, isRendering, renderChart;
      console.log("Speedometer directive linking");
      canvasId = "speedometer-" + (Date.now()) + "-" + (Math.random().toString(36).substr(2, 9));
      canvas = document.createElement('canvas');
      canvas.id = canvasId;
      canvas.width = 400;
      canvas.height = 280;
      element.append(canvas);
      chart = null;
      isRendering = false;
      destroyChart = function() {
        var e;
        if (chart != null) {
          try {
            chart.destroy();
          } catch (error1) {
            e = error1;
            console.error("Error destroying speedometer:", e);
          }
          return chart = null;
        }
      };
      renderChart = function(value, label) {
        console.log("Speedometer renderChart:", value, label);
        if (isRendering) {
          return;
        }
        isRendering = true;
        return ensureChartReady().then(function(ChartLib) {
          return $timeout(function() {
            var config, ctx, error, val;
            try {
              ctx = canvas.getContext('2d');
              if (!ctx) {
                console.error("Could not get canvas context for speedometer");
                isRendering = false;
                return;
              }
              val = parseFloat(value) || 0;
              val = Math.max(0, Math.min(100, val));
              destroyChart();
              config = {
                type: 'doughnut',
                data: {
                  datasets: [
                    {
                      data: [val, 100 - val],
                      backgroundColor: [getColorForValue(val), 'rgba(200, 200, 200, 0.2)'],
                      borderWidth: 0,
                      circumference: Math.PI,
                      rotation: Math.PI,
                      cutout: '72%'
                    }
                  ]
                },
                options: {
                  responsive: true,
                  maintainAspectRatio: true,
                  aspectRatio: 1.6,
                  layout: {
                    padding: {
                      bottom: 20
                    }
                  },
                  plugins: {
                    legend: {
                      display: false
                    },
                    tooltip: {
                      enabled: false
                    }
                  }
                },
                plugins: [
                  {
                    id: 'gaugePointer',
                    afterDatasetDraw: function(chart) {
                      var arc, endX, endY, headLength, innerRadius, meta, outerRadius, pointerAngle, pointerRadius;
                      meta = chart.getDatasetMeta(0);
                      arc = meta != null ? meta.data != null ? meta.data[0] : void 0 : void 0;
                      if (!((arc != null ? arc.startAngle : void 0) != null)) {
                        return;
                      }
                      pointerAngle = arc.endAngle;
                      if (!isFinite(pointerAngle)) {
                        pointerAngle = arc.startAngle;
                      }
                      ctx = chart.ctx;
                      outerRadius = arc.outerRadius || 0;
                      innerRadius = arc.innerRadius || 0;
                      pointerRadius = Math.max(innerRadius + (outerRadius - innerRadius) * 0.85, innerRadius + 12);
                      headLength = 12;
                      endX = arc.x + pointerRadius * Math.cos(pointerAngle);
                      endY = arc.y + pointerRadius * Math.sin(pointerAngle);
                      ctx.save();
                      ctx.lineWidth = 3;
                      ctx.lineCap = 'round';
                      ctx.strokeStyle = '#111827';
                      ctx.fillStyle = '#111827';
                      ctx.beginPath();
                      ctx.moveTo(arc.x, arc.y);
                      ctx.lineTo(endX, endY);
                      ctx.stroke();
                      ctx.beginPath();
                      ctx.moveTo(endX, endY);
                      ctx.lineTo(endX - headLength * Math.cos(pointerAngle - Math.PI / 12), endY - headLength * Math.sin(pointerAngle - Math.PI / 12));
                      ctx.lineTo(endX - headLength * Math.cos(pointerAngle + Math.PI / 12), endY - headLength * Math.sin(pointerAngle + Math.PI / 12));
                      ctx.closePath();
                      ctx.fill();
                      ctx.beginPath();
                      ctx.arc(arc.x, arc.y, 6, 0, Math.PI * 2);
                      ctx.fill();
                      return ctx.restore();
                    }
                  }
                ]
              };
              chart = new ChartLib(ctx, config);
              return console.log("✓ Speedometer created");
            } catch (error1) {
              error = error1;
              return console.error("Error creating speedometer:", error);
            } finally {
              isRendering = false;
            }
          }, 100);
        });
      };
      getColorForValue = function(value) {
        if (value < 33) {
          return 'rgba(239, 68, 68, 0.8)';
        } else if (value < 66) {
          return 'rgba(251, 191, 36, 0.8)';
        } else {
          return 'rgba(34, 197, 94, 0.8)';
        }
      };
      scope.$watch('value', function(newVal) {
        if (newVal != null) {
          return renderChart(newVal, scope.label);
        }
      });
      scope.$watch('label', function(newVal) {
        if (scope.value != null) {
          return renderChart(scope.value, newVal);
        }
      });
      return scope.$on('$destroy', function() {
        return destroyChart();
      });
    };
    return {
      restrict: 'E',
      link: link,
      scope: {
        value: '=',
        label: '@'
      }
    };
  };

  module.directive("tgSpeedometerChart", ["$parse", "$timeout", SpeedometerChartDirective]);

  PieChartDirective = function($parse, $timeout) {
    var link;
    link = function(scope, element, attrs) {
      var canvas, canvasId, chart, destroyChart, generateColors, isRendering, renderChart;
      console.log("PieChart directive linking");
      canvasId = "pie-" + (Date.now()) + "-" + (Math.random().toString(36).substr(2, 9));
      canvas = document.createElement('canvas');
      canvas.id = canvasId;
      canvas.width = 400;
      canvas.height = 400;
      element.append(canvas);
      chart = null;
      isRendering = false;
      destroyChart = function() {
        var e;
        if (chart != null) {
          try {
            chart.destroy();
          } catch (error1) {
            e = error1;
            console.error("Error destroying pie chart:", e);
          }
          return chart = null;
        }
      };
      renderChart = function(data) {
        console.log("PieChart renderChart:", data);
        if (!data) {
          destroyChart();
          return;
        }
        if (isRendering) {
          return;
        }
        isRendering = true;
        return ensureChartReady().then(function(ChartLib) {
          return $timeout(function() {
            var config, ctx, error, ref;
            try {
              ctx = canvas.getContext('2d');
              if (!ctx) {
                console.error("Could not get canvas context for pie");
                isRendering = false;
                return;
              }
              destroyChart();
              config = {
                type: 'doughnut',
                data: {
                  labels: data.labels || [],
                  datasets: [
                    {
                      data: data.values || [],
                      backgroundColor: data.colors || generateColors(((ref = data.labels) != null ? ref.length : void 0) || 0),
                      borderWidth: 2,
                      borderColor: data.borderColors || '#fff'
                    }
                  ]
                },
                options: {
                  responsive: true,
                  maintainAspectRatio: true,
                  plugins: {
                    legend: {
                      display: true,
                      position: 'bottom'
                    },
                    tooltip: {
                      callbacks: {
                        label: function(context) {
                          var i, label, len, percentage, point, ref1, ref2, total, value;
                          label = context.label || '';
                          value = context.parsed || 0;
                          total = 0;
                          ref2 = ((ref1 = context.dataset) != null ? ref1.data : void 0) || [];
                          for (i = 0, len = ref2.length; i < len; i++) {
                            point = ref2[i];
                            total += point || 0;
                          }
                          percentage = total > 0 ? ((value / total) * 100).toFixed(1) : "0.0";
                          return label + ': ' + value.toFixed(2) + ' (' + percentage + '%)';
                        }
                      }
                    }
                  }
                }
              };
              chart = new ChartLib(ctx, config);
              return console.log("✓ Pie chart created");
            } catch (error1) {
              error = error1;
              return console.error("Error creating pie chart:", error);
            } finally {
              isRendering = false;
            }
          }, 100);
        });
      };
      generateColors = function(count) {
        var colors;
        colors = ['rgba(255, 99, 132, 0.8)', 'rgba(54, 162, 235, 0.8)', 'rgba(255, 206, 86, 0.8)', 'rgba(75, 192, 192, 0.8)', 'rgba(153, 102, 255, 0.8)', 'rgba(255, 159, 64, 0.8)', 'rgba(199, 199, 199, 0.8)', 'rgba(83, 102, 255, 0.8)', 'rgba(255, 99, 255, 0.8)', 'rgba(99, 255, 132, 0.8)'];
        return colors.slice(0, count);
      };
      scope.$watch('data', function(newVal, oldVal) {
        if (newVal) {
          return renderChart(newVal);
        } else {
          return destroyChart();
        }
      }, true);
      return scope.$on('$destroy', function() {
        return destroyChart();
      });
    };
    return {
      restrict: 'E',
      link: link,
      scope: {
        data: '='
      }
    };
  };

  module.directive("tgPieChart", ["$parse", "$timeout", PieChartDirective]);

  BarChartDirective = function($parse, $timeout) {
    var link;
    link = function(scope, element, attrs) {
      var canvas, canvasId, chart, destroyChart, isRendering, renderChart;
      console.log("BarChart directive linking");
      canvasId = "bar-" + (Date.now()) + "-" + (Math.random().toString(36).substr(2, 9));
      canvas = document.createElement('canvas');
      canvas.id = canvasId;
      canvas.width = 600;
      canvas.height = 400;
      element.append(canvas);
      chart = null;
      isRendering = false;
      destroyChart = function() {
        var e;
        if (chart != null) {
          try {
            chart.destroy();
          } catch (error1) {
            e = error1;
            console.error("Error destroying bar chart:", e);
          }
          return chart = null;
        }
      };
      renderChart = function(data) {
        var config, ctx, error, ref;
        console.log("BarChart renderChart:", data);
        if (!((data != null) && data.datasets && data.datasets.length > 0)) {
          destroyChart();
          return;
        }
        if (isRendering) {
          return;
        }
        isRendering = true;
        return ensureChartReady().then(function(ChartLib) {
          return $timeout(function() {
            try {
              ctx = canvas.getContext('2d');
              if (!ctx) {
                console.error("Could not get canvas context for bar chart");
                isRendering = false;
                return;
              }
              destroyChart();
              config = {
                type: 'bar',
                data: {
                  labels: data.labels || [],
                  datasets: data.datasets || []
                },
                options: {
                  responsive: true,
                  maintainAspectRatio: true,
                  layout: {
                    padding: {
                      top: 16,
                      right: 8,
                      left: 8
                    }
                  },
                  scales: {
                    x: {
                      grid: {
                        display: false
                      },
                      ticks: {
                        color: '#1e293b',
                        font: {
                          size: 12,
                          weight: 500
                        }
                      }
                    },
                    y: {
                      beginAtZero: true,
                      min: 0,
                      max: 100,
                      ticks: {
                        stepSize: 20,
                        color: '#1e293b',
                        callback: function(value) {
                          return value + "%";
                        }
                      },
                      grid: {
                        color: 'rgba(30, 41, 59, 0.12)'
                      }
                    }
                  },
                  plugins: {
                    legend: {
                      display: true,
                      position: 'top',
                      labels: {
                        color: '#1e293b',
                        font: {
                          size: 12,
                          weight: 500
                        }
                      }
                    },
                    tooltip: {
                      callbacks: {
                        label: function(context) {
                          var label, parts, ref, ref1, value;
                          label = (ref = context.dataset) != null ? ref.label : void 0;
                          value = (ref1 = context.parsed) != null ? ref1.y : void 0;
                          parts = [];
                          if (label) {
                            parts.push(label + ":");
                          }
                          parts.push((Number(value || 0).toFixed(2)) + "%");
                          return parts.join(' ');
                        }
                      }
                    }
                  }
                }
              };
              chart = new ChartLib(ctx, config);
              return console.log("✓ Bar chart created");
            } catch (error1) {
              error = error1;
              return console.error("Error creating bar chart:", error);
            } finally {
              isRendering = false;
            }
          }, 100);
        })["catch"](function(error) {
          console.error("Chart.js not available for bar chart:", error);
          return isRendering = false;
        });
      };
      scope.$watch('data', function(newVal, oldVal) {
        if (newVal === oldVal && (chart != null)) {
          return;
        }
        if (newVal && newVal.datasets && newVal.datasets.length > 0) {
          return renderChart(newVal);
        } else {
          return destroyChart();
        }
      }, false);
      return scope.$on('$destroy', function() {
        return destroyChart();
      });
    };
    return {
      restrict: 'E',
      link: link,
      scope: {
        data: '='
      }
    };
  };

  module.directive("tgBarChart", ["$parse", "$timeout", BarChartDirective]);

  LineChartDirective = function($parse, $timeout) {
    var link;
    link = function(scope, element, attrs) {
      var canvas, canvasId, chart, destroyChart, isRendering, renderChart;
      console.log("LineChart directive linking");
      canvasId = "line-" + (Date.now()) + "-" + (Math.random().toString(36).substr(2, 9));
      canvas = document.createElement('canvas');
      canvas.id = canvasId;
      canvas.width = 600;
      canvas.height = 400;
      element.append(canvas);
      chart = null;
      isRendering = false;
      destroyChart = function() {
        var e;
        if (chart != null) {
          try {
            chart.destroy();
          } catch (error1) {
            e = error1;
            console.error("Error destroying line chart:", e);
          }
          return chart = null;
        }
      };
      renderChart = function(data) {
        console.log("LineChart renderChart:", data);
        if (!data) {
          destroyChart();
          return;
        }
        if (isRendering) {
          return;
        }
        isRendering = true;
        return ensureChartReady().then(function(ChartLib) {
          return $timeout(function() {
            var config, ctx, error, ref;
            try {
              ctx = canvas.getContext('2d');
              if (!ctx) {
                console.error("Could not get canvas context for line");
                isRendering = false;
                return;
              }
              destroyChart();
              config = {
                type: 'line',
                data: {
                  labels: data.labels || [],
                  datasets: data.datasets || []
                },
                options: {
                  responsive: true,
                  maintainAspectRatio: true,
                  scales: {
                    y: {
                      beginAtZero: true,
                      min: 0,
                      max: data.maxValue || 100,
                      ticks: {
                        callback: function(value) {
                          if (data.isPercentage) {
                            return value + '%';
                          }
                          return value;
                        }
                      }
                    },
                    x: {
                      display: true
                    }
                  },
                  plugins: {
                    legend: {
                      display: ((ref = data.datasets) != null ? ref.length : void 0) > 1,
                      position: 'bottom'
                    }
                  }
                }
              };
              chart = new ChartLib(ctx, config);
              return console.log("✓ Line chart created");
            } catch (error1) {
              error = error1;
              return console.error("Error creating line chart:", error);
            } finally {
              isRendering = false;
            }
          }, 100);
        });
      };
      scope.$watch('data', function(newVal, oldVal) {
        if (newVal) {
          return renderChart(newVal);
        } else {
          return destroyChart();
        }
      }, true);
      return scope.$on('$destroy', function() {
        return destroyChart();
      });
    };
    return {
      restrict: 'E',
      link: link,
      scope: {
        data: '='
      }
    };
  };

  module.directive("tgLineChart", ["$parse", "$timeout", LineChartDirective]);

}).call(this);
